2024-06-12 20:03:50,633 INFO    Thread-31 :27079 [wandb_setup.py:_flush():76] Current SDK version is 0.17.1
2024-06-12 20:03:50,633 INFO    Thread-31 :27079 [wandb_setup.py:_flush():76] Configure stats pid to 27079
2024-06-12 20:03:50,633 INFO    Thread-31 :27079 [wandb_setup.py:_flush():76] Loading settings from /home/ale/.config/wandb/settings
2024-06-12 20:03:50,633 INFO    Thread-31 :27079 [wandb_setup.py:_flush():76] Loading settings from /home/ale/TT_RLProject_2024/wandb/settings
2024-06-12 20:03:50,633 INFO    Thread-31 :27079 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'cm_datascience', 'entity': 'cm_datascience', 'root_dir': '/home/ale/TT_RLProject_2024', 'run_id': '85qiy7kv', 'sweep_param_path': '/home/ale/TT_RLProject_2024/wandb/sweep-z5pft0k5/config-85qiy7kv.yaml', 'sweep_id': 'z5pft0k5'}
2024-06-12 20:03:50,633 INFO    Thread-31 :27079 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-06-12 20:03:50,634 INFO    Thread-31 :27079 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'Task_4/WANDB_v1.py', 'program_abspath': '/home/ale/TT_RLProject_2024/Task_4/WANDB_v1.py', 'program': '/home/ale/TT_RLProject_2024/Task_4/WANDB_v1.py'}
2024-06-12 20:03:50,634 INFO    Thread-31 :27079 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-12 20:03:50,634 INFO    Thread-31 :27079 [wandb_init.py:_log_setup():520] Logging user logs to /home/ale/TT_RLProject_2024/wandb/run-20240612_200350-85qiy7kv/logs/debug.log
2024-06-12 20:03:50,634 INFO    Thread-31 :27079 [wandb_init.py:_log_setup():521] Logging internal logs to /home/ale/TT_RLProject_2024/wandb/run-20240612_200350-85qiy7kv/logs/debug-internal.log
2024-06-12 20:03:50,634 INFO    Thread-31 :27079 [wandb_init.py:init():560] calling init triggers
2024-06-12 20:03:50,634 INFO    Thread-31 :27079 [wandb_init.py:init():568] wandb.init called with sweep_config: {'batch_size': 128, 'clip_range': 0.3, 'ent_coef': 0.1, 'gamma': 0.95, 'learning_rate': 0.001, 'n_epochs': 15, 'n_steps': 4096, 'vf_coef': 0.35}
config: {}
2024-06-12 20:03:50,634 INFO    Thread-31 :27079 [wandb_init.py:init():610] starting backend
2024-06-12 20:03:50,634 INFO    Thread-31 :27079 [wandb_init.py:init():614] setting up manager
2024-06-12 20:03:50,636 INFO    Thread-31 :27079 [backend.py:_multiprocessing_setup():107] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-06-12 20:03:50,637 INFO    Thread-31 :27079 [wandb_init.py:init():622] backend started and connected
2024-06-12 20:03:50,641 INFO    Thread-31 :27079 [wandb_run.py:_config_callback():1382] config_cb None None {'batch_size': 128, 'clip_range': 0.3, 'ent_coef': 0.1, 'gamma': 0.95, 'learning_rate': 0.001, 'n_epochs': 15, 'n_steps': 4096, 'vf_coef': 0.35}
2024-06-12 20:03:50,641 INFO    Thread-31 :27079 [wandb_init.py:init():711] updated telemetry
2024-06-12 20:03:50,655 INFO    Thread-31 :27079 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-06-12 20:03:50,971 ERROR   Thread-31 :27079 [wandb_init.py:init():1181] error in wandb.init()
Traceback (most recent call last):
  File "/home/ale/miniconda3/envs/mldl/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 1171, in init
    return wi.init()
  File "/home/ale/miniconda3/envs/mldl/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 750, in init
    cancel=True,
  File "/home/ale/miniconda3/envs/mldl/lib/python3.7/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/home/ale/miniconda3/envs/mldl/lib/python3.7/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/home/ale/miniconda3/envs/mldl/lib/python3.7/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/home/ale/miniconda3/envs/mldl/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/home/ale/miniconda3/envs/mldl/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
Exception
2024-06-12 20:03:54,172 WARNING MsgRouterThr:27079 [router.py:message_loop():77] message_loop has been closed
